name: merculy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  fl_chart: ^0.68.0
  http: ^1.1.0
  google_sign_in: ^6.2.1
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  crypto: ^3.0.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
